on:
  workflow_dispatch:
    inputs:
      version:
        description: The new version
        required: true
jobs:
  build:
    name: Build from development
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: develop
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build, Unit Test And Static Analisi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        java -jar sonar-gate-breaker-all-1.0.1.jar -u $SONAR_TOKEN
    - name: More testing
      run: echo "More testing"
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: develop
    - name: create release branch
      run: git checkout -b release/${{ github.event.inputs.version }} develop
    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
      with:
        version: ${{ github.event.inputs.version }}
    - name: init git
      run: |
        git config user.name "GitHub actions"
        git config user.email noreply@github.com
    - name: update version
      run: echo "update version"
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add CHANGELOG.md
        git commit --message "Prepare release ${{ github.event.inputs.version }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.version }}
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        head: release/${{ github.event.inputs.version }}
        base: master
        title: Release version ${{ github.event.inputs.version }}
        reviewers: ${{ github.actor }}
        body: |-
          Hi @${{ github.actor }}!
          This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
          Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.